/**
 * Community license key for the gps-plus-slam-js core library.
 *
 * Generated by the core library maintainers and bundled with the open-source
 * `gps-plus-slam-app-framework` package so that every example app (and any
 * downstream app built on the framework) automatically uses a valid license
 * without per-developer registration.
 *
 * The key has a rolling expiration of 12 months. Each release of the
 * open-source packages renews it. Active users who regularly update their
 * dependencies will never be affected by the expiration.
 *
 * For licenses with extended validity beyond the community key's scope,
 * contact support@csutil.com.
 *
 * @see GpsPlusSlamJs/EULA.md §3 — License Key
 */

// To regenerate before expiry, use the secret-backed release/community-key
// workflow from GpsPlusSlamJs/docs/2026-04-25-private-key-security-plan.md.
// The signing private key must come from NPM_SIGNING_PRIVATE_KEY, never a
// local file.
export const COMMUNITY_LICENSE_KEY =
  'eyJ0eXBlIjoiY29tbXVuaXR5IiwiZXhwIjoxODA4NzcyNDI3fQ.YYNf0IdqniZdMzRXCuvewxsQQ01XNywrKsfL5IpiJotfFJfqtrGg4u9z0QFhXeszPtUhnvgC8_oOnbOkbXPuAw';
