/**
 * The real geoid model: EGM96, from a vendored 1-degree grid.
 *
 * WHY THIS IS A SEPARATE, OPT-IN IMPORT. The grid is ~170 KB of base64, so it
 * is deliberately NOT re-exported from `elevation/index.ts`. An app that never
 * needs absolute heights should not pay for it; an app that does imports this
 * module explicitly and gets a correct answer anywhere on Earth.
 *
 * WHY IT EXISTS AT ALL, given `geoid.ts` argued for shipping nothing. That
 * argument was never "a geoid grid is a bad idea" — it was "we must not ship
 * numbers we cannot verify", because a plausible wrong geoid is a smooth
 * confident tens-of-metres offset that looks like a GPS+SLAM fusion bug. That
 * objection is now answered rather than accepted: the grid is generated by
 * evaluating the EGM96 series to degree 360 with the reference implementation
 * already in this project (`GeoidHeights.cs`, MIT), and the tests pin it against
 * exact evaluations of that same implementation at known locations.
 *
 * Measured accuracy: **mean 0.25 m, max 5.0 m** against 600 exact evaluations.
 * The DEM being corrected has ~30 m posting and the correction itself is ~45 m
 * in central Europe, so the residual is an order of magnitude below the error it
 * removes.
 *
 * @see egm96.ts.md
 */

import type { GeoidModel } from "./geoid.js";
import { gridGeoid } from "./geoid.js";
import {
  EGM96_GRID_BASE64,
  EGM96_GRID_COLS,
  EGM96_GRID_ROWS,
  EGM96_GRID_STEP_DEG,
} from "./egm96-grid.js";

/**
 * Decodes the base64 Int16 payload.
 *
 * `atob` is used rather than `Buffer` so this works unchanged in the browser, in
 * a Worker and in Node 16+. The intermediate `Uint8Array` copy is deliberate:
 * the string's backing store is not guaranteed to be aligned for an `Int16Array`
 * view, and a misaligned view throws rather than degrading.
 */
function decodeGrid(): Int16Array {
  const binary = atob(EGM96_GRID_BASE64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);

  const expected = EGM96_GRID_ROWS * EGM96_GRID_COLS * 2;
  if (bytes.length !== expected) {
    // A truncated payload would interpolate smoothly over zeros — the exact
    // silent failure this whole area is organised around. Refuse instead.
    throw new Error(
      `EGM96 grid is ${bytes.length} bytes, expected ${expected}. The generated module is corrupt.`,
    );
  }
  return new Int16Array(bytes.buffer, bytes.byteOffset, expected / 2);
}

/** Cached because decoding allocates 130 KB and the grid never changes. */
let cached: GeoidModel | undefined;

/**
 * The EGM96 geoid, ready to pass anywhere a `GeoidModel` is wanted.
 *
 * Decoded on first call and reused thereafter.
 */
export function egm96Geoid(): GeoidModel {
  if (cached !== undefined) return cached;

  const decimetres = decodeGrid();
  // Values are stored in decimetres; the grid model wants metres.
  const metres = new Float32Array(decimetres.length);
  for (let i = 0; i < decimetres.length; i++) {
    metres[i] = (decimetres[i] ?? 0) / 10;
  }

  cached = gridGeoid({
    id: "EGM96 (1° grid, mean 0.25 m / max 5.0 m vs. exact)",
    stepDeg: EGM96_GRID_STEP_DEG,
    northLat: 90,
    westLng: 0,
    rows: EGM96_GRID_ROWS,
    cols: EGM96_GRID_COLS,
    values: metres,
  });
  return cached;
}
