/**
 * Tests for `qr-derived-pose.ts` — the derive-on-read (D-A) layer.
 *
 * Why this matters: the recorder live-QR plan records the RAW detector output
 * (corners + camera pose + projection + frame size) and derives the metric size
 * and solved pose on read, so swapping the size/PnP algorithm and re-running a
 * recording yields a NEW result. These tests pin:
 *   1. the as-of depth join is replayed over the whole history to accumulate size,
 *   2. the pose is solved from the LATEST raw observation + that size,
 *   3. the re-test guarantee: a raw observation generated by forward-projecting a
 *      known pose re-derives that same pose (live == replay by construction),
 *   4. graceful nulls when there is no history / no depth / size not yet known.
 *
 * @see docs 2026-06-17-recorder-live-qr-detection-recording-plan.md (WS-4, D-A).
 */

import { describe, it, expect } from 'vitest';
import { quat } from 'gl-matrix';
import type { Matrix4, Quaternion, Vector3 } from 'gps-plus-slam-js';
import {
  buildObjectPoints,
  projectViewPoint,
  transformPoint,
  composePose,
  type Point2,
  type Pose,
  type SolvePnpSquare,
  type OpenCvPnpResult,
} from './qr-pose.js';
import { PlanarPnpSquare } from './planar-pnp.js';
import type { QrSizeDepthContext } from './qr-size-measurer.js';
import {
  deriveQrSizeM,
  deriveSolvedQrPose,
  deriveQrPlacement,
  createIncrementalQrPlacement,
  solveQrPoseFromObservation,
  type RawQrObservation,
} from './qr-derived-pose.js';

// --- Helpers ----------------------------------------------------------------

/** Build a column-major GL projection matrix that inverts `intrinsicsFromProjection`. */
function projectionFromIntrinsics(
  fx: number,
  fy: number,
  cx: number,
  cy: number,
  width: number,
  height: number
): Matrix4 {
  const m: number[] = new Array(16).fill(0);
  m[0] = (2 * fx) / width;
  m[5] = (2 * fy) / height;
  m[8] = 1 - (2 * cx) / width;
  m[9] = (2 * cy) / height - 1;
  m[10] = -1;
  m[11] = -1;
  return m as unknown as Matrix4;
}

const W = 640;
const H = 480;
const INTR = { fx: 600, fy: 600, cx: 320, cy: 240 };
const PROJ = projectionFromIntrinsics(INTR.fx, INTR.fy, INTR.cx, INTR.cy, W, H);

const cameraPose: Pose = {
  position: [1, 2, 3] as Vector3,
  rotation: [0, 0, 0, 1] as Quaternion,
};

/**
 * An "exact" solver: returns the OpenCV (rvec,tvec) corresponding to a chosen
 * WebXR `qrPoseInCamera` (inverts `qrInCameraFromOpenCv`: R_ocv = Rx(π)·R_webxr,
 * t_ocv = (t0,−t1,−t2)). Isolates the derive wiring from PnP numerics (the real
 * PnP is exercised in the round-trip test). Mirrors qr-pose.test.ts.
 */
function makeExactSolver(qrPoseInCamera: Pose): SolvePnpSquare {
  return {
    solve(): OpenCvPnpResult {
      const rxPi = quat.fromValues(1, 0, 0, 0);
      const qWebxr = quat.fromValues(
        qrPoseInCamera.rotation[0],
        qrPoseInCamera.rotation[1],
        qrPoseInCamera.rotation[2],
        qrPoseInCamera.rotation[3]
      );
      const qOcv = quat.multiply(quat.create(), rxPi, qWebxr);
      const angle = 2 * Math.acos(Math.min(1, Math.abs(qOcv[3])));
      const s = Math.sqrt(1 - qOcv[3] * qOcv[3]);
      const sign = qOcv[3] < 0 ? -1 : 1;
      const rvec: Vector3 =
        s < 1e-9
          ? [0, 0, 0]
          : [
              (sign * qOcv[0] * angle) / s,
              (sign * qOcv[1] * angle) / s,
              (sign * qOcv[2] * angle) / s,
            ];
      const t = qrPoseInCamera.position;
      return { rvec, tvec: [t[0], -t[1], -t[2]] };
    },
  };
}

/** Forward-project a known QR pose to the 4 detected corner pixels. */
function projectedCorners(qrPoseInCamera: Pose, sizeM: number): Point2[] {
  return buildObjectPoints(sizeM).map(
    (obj) =>
      projectViewPoint(transformPoint(obj, qrPoseInCamera), INTR) as Point2
  );
}

function makeObservation(
  text: string,
  corners: readonly Point2[],
  timestamp: number
): RawQrObservation {
  return {
    text,
    corners,
    cameraPose,
    projectionMatrix: PROJ,
    imageWidth: W,
    imageHeight: H,
    timestamp,
  };
}

/** A depth context that returns a constant depth everywhere (a fronto-parallel
 * plane at `depthM`) and an unprojector consistent with INTR/cameraPose. */
function constantDepthContext(depthM: number): QrSizeDepthContext {
  return {
    depthAt: () => depthM,
    // Unproject a normalized screen point at the given depth into a 3D point in
    // raw-WebXR space. Mirrors createDepthUnprojector for INTR + cameraPose with
    // identity rotation: screen → camera ray → world (camera at cameraPose).
    unprojector: {
      unproject: ({ screenX, screenY, depthM: d }) => {
        const px = screenX * W;
        const py = screenY * H;
        // Pinhole inverse (camera frame, +x right, +y up, -z forward).
        const xCam = ((px - INTR.cx) * d) / INTR.fx;
        const yCam = (-(py - INTR.cy) * d) / INTR.fy;
        const zCam = -d;
        // Identity camera rotation → just translate by camera position.
        return [
          cameraPose.position[0] + xCam,
          cameraPose.position[1] + yCam,
          cameraPose.position[2] + zCam,
        ] as Vector3;
      },
    },
  };
}

// --- Tests ------------------------------------------------------------------

describe('deriveQrSizeM', () => {
  it('returns null with no observations', () => {
    expect(deriveQrSizeM('m', [], () => constantDepthContext(1))).toBeNull();
  });

  it('returns null when depth is never resolvable', () => {
    const corners = projectedCorners(
      { position: [0, 0, -1] as Vector3, rotation: [0, 0, 0, 1] as Quaternion },
      0.2
    );
    const obs = [makeObservation('m', corners, 10)];
    expect(deriveQrSizeM('m', obs, () => null)).toBeNull();
  });
});

describe('solveQrPoseFromObservation', () => {
  it('solves the world pose from one raw observation + a known size (exact solver)', () => {
    const sizeM = 0.2;
    const qrPoseInCamera: Pose = {
      position: [0.05, -0.03, -0.8] as Vector3,
      rotation: [0, 0, 0, 1] as Quaternion,
    };
    const corners = projectedCorners(qrPoseInCamera, sizeM);
    const obs = makeObservation('m', corners, 1);

    const pose = solveQrPoseFromObservation(
      obs,
      sizeM,
      makeExactSolver(qrPoseInCamera)
    );
    expect(pose).not.toBeNull();
    const expectedWorld = composePose(cameraPose, qrPoseInCamera);
    for (let i = 0; i < 3; i++) {
      expect(pose!.position[i]).toBeCloseTo(expectedWorld.position[i], 5);
    }
  });
});

describe('deriveSolvedQrPose', () => {
  it('returns null for an empty history', () => {
    expect(
      deriveSolvedQrPose('m', [], {
        resolveDepthAt: () => constantDepthContext(1),
        solver: new PlanarPnpSquare(),
      })
    ).toBeNull();
  });

  it('returns null when size cannot be derived (no depth)', () => {
    const corners = projectedCorners(
      {
        position: [0, 0, -0.8] as Vector3,
        rotation: [0, 0, 0, 1] as Quaternion,
      },
      0.2
    );
    expect(
      deriveSolvedQrPose('m', [makeObservation('m', corners, 1)], {
        resolveDepthAt: () => null,
        solver: new PlanarPnpSquare(),
      })
    ).toBeNull();
  });

  it('re-derives the known pose end-to-end with the REAL PnP + depth (the re-test guarantee)', () => {
    // A fronto-parallel QR 0.8 m in front of the camera, side 0.2 m. The constant
    // depth context places its plane at 0.8 m, so the derived size ≈ 0.2 m and the
    // PnP recovers the pose we projected from — proving live == replay.
    const sizeM = 0.2;
    const distance = 0.8;
    const qrPoseInCamera: Pose = {
      position: [0, 0, -distance] as Vector3,
      rotation: [0, 0, 0, 1] as Quaternion,
    };
    const corners = projectedCorners(qrPoseInCamera, sizeM);
    // A few observations of the same fixed marker (history accumulates size).
    const obs = [10, 20, 30].map((t) => makeObservation('m', corners, t));

    const pose = deriveSolvedQrPose('m', obs, {
      resolveDepthAt: () => constantDepthContext(distance),
      solver: new PlanarPnpSquare(),
    });
    expect(pose).not.toBeNull();
    const expectedWorld = composePose(cameraPose, qrPoseInCamera);
    for (let i = 0; i < 3; i++) {
      expect(pose!.position[i]).toBeCloseTo(expectedWorld.position[i], 2);
    }
  });
});

describe('deriveQrPlacement', () => {
  it('returns null for an empty history and when no depth resolves', () => {
    const deps = {
      resolveDepthAt: () => constantDepthContext(1),
      solver: new PlanarPnpSquare(),
    };
    expect(deriveQrPlacement('m', [], deps)).toBeNull();
    const corners = projectedCorners(
      {
        position: [0, 0, -0.8] as Vector3,
        rotation: [0, 0, 0, 1] as Quaternion,
      },
      0.2
    );
    expect(
      deriveQrPlacement('m', [makeObservation('m', corners, 1)], {
        resolveDepthAt: () => null,
        solver: new PlanarPnpSquare(),
      })
    ).toBeNull();
  });

  it('returns BOTH the pose and the size that solved it (the cube needs the size)', () => {
    // Same fronto-parallel marker as the re-test guarantee: the placement must
    // carry the derived metric side (≈0.2 m) alongside the recovered pose, so the
    // debug cube can be scaled without a second history pass.
    const sizeM = 0.2;
    const distance = 0.8;
    const qrPoseInCamera: Pose = {
      position: [0, 0, -distance] as Vector3,
      rotation: [0, 0, 0, 1] as Quaternion,
    };
    const corners = projectedCorners(qrPoseInCamera, sizeM);
    const obs = [10, 20, 30].map((t) => makeObservation('m', corners, t));

    const placement = deriveQrPlacement('m', obs, {
      resolveDepthAt: () => constantDepthContext(distance),
      solver: new PlanarPnpSquare(),
    });
    expect(placement).not.toBeNull();
    expect(placement!.sizeM).toBeCloseTo(sizeM, 2);
    // The pose matches what deriveSolvedQrPose returns (placement.pose IS it).
    const expectedWorld = composePose(cameraPose, qrPoseInCamera);
    for (let i = 0; i < 3; i++) {
      expect(placement!.pose.position[i]).toBeCloseTo(
        expectedWorld.position[i],
        2
      );
    }
  });
});

describe('createIncrementalQrPlacement', () => {
  // A fronto-parallel marker (the re-test fixture) so both the incremental and
  // the full-replay path can size + solve it deterministically.
  const SIZE = 0.2;
  const DIST = 0.8;
  const incQrPoseInCamera: Pose = {
    position: [0, 0, -DIST] as Vector3,
    rotation: [0, 0, 0, 1] as Quaternion,
  };
  const incCorners = projectedCorners(incQrPoseInCamera, SIZE);
  const growingHistory = (n: number): RawQrObservation[] =>
    Array.from({ length: n }, (_, i) =>
      makeObservation('m', incCorners, 10 * (i + 1))
    );

  it('matches deriveQrPlacement (full replay) after folding the whole history', () => {
    const obs = growingHistory(5);
    const deps = {
      resolveDepthAt: () => constantDepthContext(DIST),
      solver: new PlanarPnpSquare(),
    };
    const inc = createIncrementalQrPlacement(deps);
    // Drive incrementally, one observation at a time (the live cadence).
    let live: ReturnType<typeof inc.update> = null;
    for (let i = 1; i <= obs.length; i++)
      live = inc.update('m', obs.slice(0, i));

    const replay = deriveQrPlacement('m', obs, deps);
    expect(live).not.toBeNull();
    expect(replay).not.toBeNull();
    expect(live!.sizeM).toBeCloseTo(replay!.sizeM, 6);
    for (let i = 0; i < 3; i++) {
      expect(live!.pose.position[i]).toBeCloseTo(replay!.pose.position[i], 6);
    }
  });

  /**
   * Why this test matters (the perf-degradation fix): the OLD store-driven viz
   * re-folded the WHOLE history on every call — O(history) per store action,
   * total O(N²) over a growing marker. The incremental deriver folds each
   * observation EXACTLY ONCE. We count depth resolutions (one per folded
   * observation): after N incremental updates over a growing history, the total
   * must be N (linear), NOT N(N+1)/2 (quadratic).
   */
  it('folds each observation exactly once — cost is O(1) per new detection', () => {
    let depthCalls = 0;
    const inc = createIncrementalQrPlacement({
      resolveDepthAt: () => {
        depthCalls += 1;
        return constantDepthContext(DIST);
      },
      solver: new PlanarPnpSquare(),
    });
    const N = 12;
    for (let i = 1; i <= N; i++) inc.update('m', growingHistory(i));
    expect(depthCalls).toBe(N); // linear — a full replay would be N*(N+1)/2 = 78
  });

  it('memoizes when no new observation arrived (F1) — no fold, no re-derive', () => {
    let depthCalls = 0;
    const inc = createIncrementalQrPlacement({
      resolveDepthAt: () => {
        depthCalls += 1;
        return constantDepthContext(DIST);
      },
      solver: new PlanarPnpSquare(),
    });
    const obs = growingHistory(3);
    const first = inc.update('m', obs);
    const callsAfterFirst = depthCalls; // 3 (folded all three)
    const second = inc.update('m', obs); // same newest timestamp → no fold
    expect(depthCalls).toBe(callsAfterFirst); // unchanged — nothing re-folded
    expect(second).toEqual(first); // cached placement returned
  });

  it('reset(text) clears the accumulated size so folding starts over', () => {
    let depthCalls = 0;
    const inc = createIncrementalQrPlacement({
      resolveDepthAt: () => {
        depthCalls += 1;
        return constantDepthContext(DIST);
      },
      solver: new PlanarPnpSquare(),
    });
    inc.update('m', growingHistory(3));
    expect(depthCalls).toBe(3);
    inc.reset('m');
    // After reset, the same observations are folded again (cursor cleared).
    inc.update('m', growingHistory(3));
    expect(depthCalls).toBe(6);
  });

  it('returns null until a marker can be sized, without throwing', () => {
    const inc = createIncrementalQrPlacement({
      resolveDepthAt: () => null, // never resolvable → never sizeable
      solver: new PlanarPnpSquare(),
    });
    expect(inc.update('m', growingHistory(3))).toBeNull();
    expect(inc.update('m', [])).toBeNull();
  });

  /**
   * Why this test matters: the as-of depth join (`resolveDepthAt`) is fed by a
   * SEPARATE async stream, so a freshly-detected observation can transiently
   * have no depth sample ≤ its timestamp yet (returns null) and become resolvable
   * a tick later. The fold cursor (`lastFoldedTs`) must only advance past
   * observations it actually folded — otherwise a depth-less observation is
   * permanently skipped (its size contribution lost forever) even once its depth
   * arrives, because F1 short-circuits on `newestTs <= foldedTs`.
   */
  it('retries depth-less observations once their depth becomes available', () => {
    let depthReady = false;
    const inc = createIncrementalQrPlacement({
      resolveDepthAt: () => (depthReady ? constantDepthContext(DIST) : null),
      solver: new PlanarPnpSquare(),
    });
    const obs = growingHistory(5);

    // First pass: depth not yet available → every observation is skipped, so the
    // marker is not sizeable and the cursor must NOT advance past them.
    expect(inc.update('m', obs)).toBeNull();

    // Depth now available: the SAME observations must be folded and solved.
    depthReady = true;
    const placement = inc.update('m', obs);
    expect(placement).not.toBeNull();
    expect(placement!.sizeM).toBeCloseTo(SIZE, 2);
  });
});
