/**
 * Tests for `qr-derived-pose.ts` — the derive-on-read (D-A) layer.
 *
 * Why this matters: the recorder live-QR plan records the RAW detector output
 * (corners + camera pose + projection + frame size) and derives the metric size
 * and solved pose on read, so swapping the size/PnP algorithm and re-running a
 * recording yields a NEW result. These tests pin:
 *   1. the as-of depth join is replayed over the whole history to accumulate size,
 *   2. the pose is solved from the LATEST raw observation + that size,
 *   3. the re-test guarantee: a raw observation generated by forward-projecting a
 *      known pose re-derives that same pose (live == replay by construction),
 *   4. graceful nulls when there is no history / no depth / size not yet known.
 *
 * @see docs 2026-06-17-recorder-live-qr-detection-recording-plan.md (WS-4, D-A).
 */

import { describe, it, expect } from 'vitest';
import { quat } from 'gl-matrix';
import type { Matrix4, Quaternion, Vector3 } from 'gps-plus-slam-js';
import {
  buildObjectPoints,
  projectViewPoint,
  transformPoint,
  composePose,
  type Point2,
  type Pose,
  type SolvePnpSquare,
  type OpenCvPnpResult,
} from './qr-pose.js';
import { PlanarPnpSquare } from './planar-pnp.js';
import type { QrSizeDepthContext } from './qr-size-measurer.js';
import {
  deriveQrSizeM,
  deriveSolvedQrPose,
  solveQrPoseFromObservation,
  type RawQrObservation,
} from './qr-derived-pose.js';

// --- Helpers ----------------------------------------------------------------

/** Build a column-major GL projection matrix that inverts `intrinsicsFromProjection`. */
function projectionFromIntrinsics(
  fx: number,
  fy: number,
  cx: number,
  cy: number,
  width: number,
  height: number
): Matrix4 {
  const m: number[] = new Array(16).fill(0);
  m[0] = (2 * fx) / width;
  m[5] = (2 * fy) / height;
  m[8] = 1 - (2 * cx) / width;
  m[9] = (2 * cy) / height - 1;
  m[10] = -1;
  m[11] = -1;
  return m as unknown as Matrix4;
}

const W = 640;
const H = 480;
const INTR = { fx: 600, fy: 600, cx: 320, cy: 240 };
const PROJ = projectionFromIntrinsics(INTR.fx, INTR.fy, INTR.cx, INTR.cy, W, H);

const cameraPose: Pose = {
  position: [1, 2, 3] as Vector3,
  rotation: [0, 0, 0, 1] as Quaternion,
};

/**
 * An "exact" solver: returns the OpenCV (rvec,tvec) corresponding to a chosen
 * WebXR `qrPoseInCamera` (inverts `qrInCameraFromOpenCv`: R_ocv = Rx(π)·R_webxr,
 * t_ocv = (t0,−t1,−t2)). Isolates the derive wiring from PnP numerics (the real
 * PnP is exercised in the round-trip test). Mirrors qr-pose.test.ts.
 */
function makeExactSolver(qrPoseInCamera: Pose): SolvePnpSquare {
  return {
    solve(): OpenCvPnpResult {
      const rxPi = quat.fromValues(1, 0, 0, 0);
      const qWebxr = quat.fromValues(
        qrPoseInCamera.rotation[0],
        qrPoseInCamera.rotation[1],
        qrPoseInCamera.rotation[2],
        qrPoseInCamera.rotation[3]
      );
      const qOcv = quat.multiply(quat.create(), rxPi, qWebxr);
      const angle = 2 * Math.acos(Math.min(1, Math.abs(qOcv[3])));
      const s = Math.sqrt(1 - qOcv[3] * qOcv[3]);
      const sign = qOcv[3] < 0 ? -1 : 1;
      const rvec: Vector3 =
        s < 1e-9
          ? [0, 0, 0]
          : [
              (sign * qOcv[0] * angle) / s,
              (sign * qOcv[1] * angle) / s,
              (sign * qOcv[2] * angle) / s,
            ];
      const t = qrPoseInCamera.position;
      return { rvec, tvec: [t[0], -t[1], -t[2]] };
    },
  };
}

/** Forward-project a known QR pose to the 4 detected corner pixels. */
function projectedCorners(qrPoseInCamera: Pose, sizeM: number): Point2[] {
  return buildObjectPoints(sizeM).map(
    (obj) =>
      projectViewPoint(transformPoint(obj, qrPoseInCamera), INTR) as Point2
  );
}

function makeObservation(
  text: string,
  corners: readonly Point2[],
  timestamp: number
): RawQrObservation {
  return {
    text,
    corners,
    cameraPose,
    projectionMatrix: PROJ,
    imageWidth: W,
    imageHeight: H,
    timestamp,
  };
}

/** A depth context that returns a constant depth everywhere (a fronto-parallel
 * plane at `depthM`) and an unprojector consistent with INTR/cameraPose. */
function constantDepthContext(depthM: number): QrSizeDepthContext {
  return {
    depthAt: () => depthM,
    // Unproject a normalized screen point at the given depth into a 3D point in
    // raw-WebXR space. Mirrors createDepthUnprojector for INTR + cameraPose with
    // identity rotation: screen → camera ray → world (camera at cameraPose).
    unprojector: {
      unproject: ({ screenX, screenY, depthM: d }) => {
        const px = screenX * W;
        const py = screenY * H;
        // Pinhole inverse (camera frame, +x right, +y up, -z forward).
        const xCam = ((px - INTR.cx) * d) / INTR.fx;
        const yCam = (-(py - INTR.cy) * d) / INTR.fy;
        const zCam = -d;
        // Identity camera rotation → just translate by camera position.
        return [
          cameraPose.position[0] + xCam,
          cameraPose.position[1] + yCam,
          cameraPose.position[2] + zCam,
        ] as Vector3;
      },
    },
  };
}

// --- Tests ------------------------------------------------------------------

describe('deriveQrSizeM', () => {
  it('returns null with no observations', () => {
    expect(deriveQrSizeM('m', [], () => constantDepthContext(1))).toBeNull();
  });

  it('returns null when depth is never resolvable', () => {
    const corners = projectedCorners(
      { position: [0, 0, -1] as Vector3, rotation: [0, 0, 0, 1] as Quaternion },
      0.2
    );
    const obs = [makeObservation('m', corners, 10)];
    expect(deriveQrSizeM('m', obs, () => null)).toBeNull();
  });
});

describe('solveQrPoseFromObservation', () => {
  it('solves the world pose from one raw observation + a known size (exact solver)', () => {
    const sizeM = 0.2;
    const qrPoseInCamera: Pose = {
      position: [0.05, -0.03, -0.8] as Vector3,
      rotation: [0, 0, 0, 1] as Quaternion,
    };
    const corners = projectedCorners(qrPoseInCamera, sizeM);
    const obs = makeObservation('m', corners, 1);

    const pose = solveQrPoseFromObservation(
      obs,
      sizeM,
      makeExactSolver(qrPoseInCamera)
    );
    expect(pose).not.toBeNull();
    const expectedWorld = composePose(cameraPose, qrPoseInCamera);
    for (let i = 0; i < 3; i++) {
      expect(pose!.position[i]).toBeCloseTo(expectedWorld.position[i], 5);
    }
  });
});

describe('deriveSolvedQrPose', () => {
  it('returns null for an empty history', () => {
    expect(
      deriveSolvedQrPose('m', [], {
        resolveDepthAt: () => constantDepthContext(1),
        solver: new PlanarPnpSquare(),
      })
    ).toBeNull();
  });

  it('returns null when size cannot be derived (no depth)', () => {
    const corners = projectedCorners(
      {
        position: [0, 0, -0.8] as Vector3,
        rotation: [0, 0, 0, 1] as Quaternion,
      },
      0.2
    );
    expect(
      deriveSolvedQrPose('m', [makeObservation('m', corners, 1)], {
        resolveDepthAt: () => null,
        solver: new PlanarPnpSquare(),
      })
    ).toBeNull();
  });

  it('re-derives the known pose end-to-end with the REAL PnP + depth (the re-test guarantee)', () => {
    // A fronto-parallel QR 0.8 m in front of the camera, side 0.2 m. The constant
    // depth context places its plane at 0.8 m, so the derived size ≈ 0.2 m and the
    // PnP recovers the pose we projected from — proving live == replay.
    const sizeM = 0.2;
    const distance = 0.8;
    const qrPoseInCamera: Pose = {
      position: [0, 0, -distance] as Vector3,
      rotation: [0, 0, 0, 1] as Quaternion,
    };
    const corners = projectedCorners(qrPoseInCamera, sizeM);
    // A few observations of the same fixed marker (history accumulates size).
    const obs = [10, 20, 30].map((t) => makeObservation('m', corners, t));

    const pose = deriveSolvedQrPose('m', obs, {
      resolveDepthAt: () => constantDepthContext(distance),
      solver: new PlanarPnpSquare(),
    });
    expect(pose).not.toBeNull();
    const expectedWorld = composePose(cameraPose, qrPoseInCamera);
    for (let i = 0; i < 3; i++) {
      expect(pose!.position[i]).toBeCloseTo(expectedWorld.position[i], 2);
    }
  });
});
